/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import Dao.Statistics;
import Dao.SupplierDao;
import Users.LogIn;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Laptop
 */
public class ManageSupplier extends javax.swing.JFrame {

    /**
     * Creates new form ManageSupplier
     */
    SupplierDao supplier = new SupplierDao();
    DefaultTableModel model;
    int rowIndex;
    Statistics statistics = new Statistics();
    public ManageSupplier() {
        initComponents();
        supplierTable();
        setLocation(450,110);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        eye = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        supplier_t = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 365, 30));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 365, 30));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 365, 30));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 365, 30));

        pass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 365, 30));

        jTextField6.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 365, 30));

        jTextField7.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 365, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Supplier ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 50, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Email");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Password");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Phone Number");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 140, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Adresss Street,Zone");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 170, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Adress Barangay");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, -1));

        update.setBackground(new java.awt.Color(0, 0, 0));
        update.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel2.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 131, 36));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/no.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 6, 65, -1));

        eye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hide.png"))); // NOI18N
        eye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeMouseClicked(evt);
            }
        });
        jPanel2.add(eye, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 43, -1));

        delete.setBackground(new java.awt.Color(0, 0, 0));
        delete.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel2.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 132, 34));

        clear.setBackground(new java.awt.Color(0, 0, 0));
        clear.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel2.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 150, 34));

        supplier_t.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier ID", "Supplier Name", "Email", "Password", "Phone Number", "Address Street,Zone", "Address Barangay"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        supplier_t.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplier_tMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(supplier_t);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 750, 350));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("____________________________________________________________________________________________________________________________________________________________________");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 48, 30));

        jTextField9.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField9KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 257, 30));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MANAGE SUPPLIER");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 837, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 812, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
     private void supplierTable() {
       supplier.getSupplierValue(supplier_t,"");
        model = (DefaultTableModel) supplier_t.getModel();
        supplier_t.setRowHeight(30);
        supplier_t.setShowGrid(true);
     }
     private void clear(){
         jTextField1.setText("");
         jTextField2.setText("");
         jTextField3.setText("");
         pass.setText("");
         jTextField4.setText("");
         jTextField6.setText("");
         jTextField7.setText("");
         supplier_t.clearSelection();
         statistics.admin();
     }
     
    private boolean isEmpty() {
        
        if (jTextField1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a user ");
            return false;
        }

        // Check if Username is empty
        if (jTextField2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "User Name is required", "Warning", 2);
            return false;
        }

        // Check if Email is empty or invalid
        if (jTextField3.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Invalid Email address is required", "Warning", 2);
            return false;
        }

        // Check if Password is empty
        if (String.valueOf(pass.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password is required", "Warning", 2);
            return false;
        }

        // Check if Phone Number is empty or invalid
        String phone = jTextField4.getText();
        if (phone.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Phone Number is required", "Warning", 2);
            return false;
        }
        if (phone.length() < 10 || phone.length() > 15) {
            JOptionPane.showMessageDialog(this, "Phone Number should be between 10 and 15 characters", "Warning", 2);
            return false;
        }
        if (pass.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Answer for Security Question is Required", "Warning", 2);
            return false;
        }

        // Check if Address fields are empty
        if (jTextField6.getText().isEmpty() || jTextField7.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Both address fields are required", "Warning", 2);
            return false;
        }

        return true;
    }
        
    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
   this.setVisible(false);  
    }//GEN-LAST:event_jLabel11MouseClicked

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void supplier_tMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_tMouseClicked
        model = (DefaultTableModel) supplier_t.getModel();
         rowIndex = supplier_t.getSelectedRow();
        jTextField1.setText(model.getValueAt(rowIndex, 0).toString());
        jTextField2.setText(model.getValueAt(rowIndex, 1).toString());
        jTextField3.setText(model.getValueAt(rowIndex, 2).toString());
       pass.setText(model.getValueAt(rowIndex, 3).toString());
        jTextField4.setText(model.getValueAt(rowIndex, 4).toString());
        jTextField6.setText(model.getValueAt(rowIndex, 5).toString());
        jTextField7.setText(model.getValueAt(rowIndex, 6).toString());
       
    }//GEN-LAST:event_supplier_tMouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed

if (isEmpty()) {
        if(!check()){
    // Placeholder UI components for inputs (replace with your actual components)
    int ID = Integer.parseInt(jTextField1.getText()); // Get integer value from JTextField
    String Suppliername = jTextField2.getText();         // Get string value from JTextField
    String Email = jTextField3.getText();            // Get string value from JTextField
    String Password = String.valueOf(pass.getPassword()); // Get password from JPasswordField
    String Phone = jTextField4.getText();              
    String Adds1 = jTextField6.getText();
     String Adds2 = jTextField7.getText(); 
    supplier.update(ID, Suppliername, Email, Password, Phone,Adds1, Adds2);
     supplier_t.setModel(new DefaultTableModel(null, new Object[]{"Supplier ID","Name","Email","Password","Phone Number","Address1","Address2"}));
        supplier.getSupplierValue(supplier_t,"");
        
    }  
       }
    }//GEN-LAST:event_updateActionPerformed

    private void jTextField9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyReleased
         supplier_t.setModel(new DefaultTableModel(null, new Object[]{"User ID","Username","Email","Password","Phone Number","Address1","Address2"}));
        supplier.getSupplierValue(supplier_t,jTextField9.getText());
    }//GEN-LAST:event_jTextField9KeyReleased

    private void eyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeMouseClicked
          if (pass.getEchoChar() != (char) 0) {
            pass.setEchoChar((char) 0);  // Show password
            eye.setVisible(true);       // Show the "eye" icon or button
        } else {
            pass.setEchoChar('●');     // Replace '●' with your desired echo character for hiding
            eye.setVisible(true);     // Hide the "eye" icon or button
        }
    }//GEN-LAST:event_eyeMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
         // TODO add your handling code here:
          if(isEmpty()){
      int id = Integer.parseInt(jTextField1.getText());
      supplier.delete(id);
       supplier_t.setModel(new DefaultTableModel(null, new Object[]{"Supplier ID","Supplier Name","Email","Password","Phone Number", "Address1","Address2"}));
        supplier.getSupplierValue(supplier_t,"");
      clear();
      }
        
        
    }//GEN-LAST:event_deleteActionPerformed

    
    
     private boolean check() {
    String newUsername = jTextField3.getText();
    String newEmail = jTextField3.getText();  // Corrected syntax: Removed "new"
    String newPhone = jTextField4.getText();  // Corrected syntax: Removed "new"
    String oldUsername = model.getValueAt(rowIndex,1).toString();
    String oldEmail = model.getValueAt(rowIndex,2).toString();
    String oldPhone = model.getValueAt(rowIndex,4).toString();
    

    // Check if both email and phone match the existing values (value[2] and value[4])
    if (newUsername.equals(oldUsername) && newEmail.equals(oldEmail)&& newPhone.equals(oldPhone)) {
        return false;  // No changes made to email and phone
    } else {
         if (!newUsername.equals(oldUsername)) {
            boolean x = supplier.isUsernameExist(newUsername);
            if (x) {
                JOptionPane.showMessageDialog(this, "This username already exists", "Warning", JOptionPane.WARNING_MESSAGE);
            }
            return x;  // Return whether the email exists
        }
        // Check if email is different and already exists in the system
        if (!newEmail.equals(oldEmail)) {
            boolean x = supplier.isEmailExist(newEmail);
            if (x) {
                JOptionPane.showMessageDialog(this, "This email already exists", "Warning", JOptionPane.WARNING_MESSAGE);
            }
            return x;  // Return whether the email exists
        }
        // Check if phone is different and already exists in the system
        if (!newPhone.equals(oldPhone)) {
            boolean x = supplier.isPhoneExist(newPhone);
            if (x) {
                JOptionPane.showMessageDialog(this, "This phone number already exists", "Warning", JOptionPane.WARNING_MESSAGE);
            }
            return x;  // Return whether the phone number exists
        }
    }
    
    return false;  // No issues, everything is fine
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JLabel eye;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTable supplier_t;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
